dict {}

{'_api': <tweepy.api.API object at 0x0000013ABA613A60>, 
'_json': {
    'created_at': 'Wed Oct 28 23:59:50 +0000 2020', 
    'id': 1321602608663068673, 
    'id_str': '1321602608663068673', 
    'text': '5 Genius Ways to Minimize Risk As An Options Trader\n\nhttps://t.co/3SikjPSsxk\n\n$spy $aapl $tsla', 
    'source': '<a href="https://stocktwits.com" rel="nofollow">StockTwits Web</a>', 
    'truncated': False, 
    'in_reply_to_status_id': None, 
    'in_reply_to_status_id_str': None, 
    'in_reply_to_user_id': None, 
    'in_reply_to_user_id_str': None, 
    'in_reply_to_screen_name': None, 
    'user': {
        'id': 950402063271424003, 
        'id_str': '950402063271424003', 
        'name': 'SmartOptions® Ai', 
        'screen_name': 'SmartOptionsAi', 
        'location': None, 
        'url': 'https://www.smartoptions.ai', 
        'description': 'CEO of SmartOptions®. Made millions in the market. Highly Profitable Options Signals Powered by Artificial Intelligence.',
        'translator_type': 'none', 
        'protected': False, 
        'verified': False, 
        'followers_count': 3285, 
        'friends_count': 74, 
        'listed_count': 47, 
        'favourites_count': 583, 
        'statuses_count': 3908, 
        'created_at': 'Mon Jan 08 16:21:24 +0000 2018', 
        'utc_offset': None, 
        'time_zone': None, 
        'geo_enabled': False, 
        'lang': None, 
        'contributors_enabled': False, 
        'is_translator': False, 
        'profile_background_color': '000000', 
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': False, 
        'profile_link_color': '1B95E0', 
        'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 
        'profile_text_color': '000000', 
        'profile_use_background_image': False, 
        'profile_image_url': 'http://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', 
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', 
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/950402063271424003/1599668618', 
        'default_profile': False, 'default_profile_image': False, 'following': None, 'follow_request_sent': None, 
        'notifications': None
    }, 
    'geo': None, 'coordinates': None, 'place': None, 'contributors': None, 
    'is_quote_status': False, 'quote_count': 0, 'reply_count': 0, 'retweet_count': 0, 'favorite_count': 0, 
    'entities': {
        'hashtags': [], 'urls': [{'url': 'https://t.co/3SikjPSsxk', 'expanded_url': 'http://smartoptions.ai/post/minimize-risk', 'display_url': 'smartoptions.ai/post/minimize-…', 'indices': [53, 76]}], 'user_mentions': [], 'symbols': [{'text': 'spy', 'indices': [78, 82]}, {'text': 'aapl', 'indices': [83, 88]}, {'text': 'tsla', 'indices': [89, 94]}]}, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'filter_level': 'low', 'lang': 'en', 'matching_rules': [{'tag': None}]}, 'created_at': datetime.datetime(2020, 10, 28, 23, 59, 50), 'id': 1321602608663068673, 'id_str': '1321602608663068673', 'text': '5 Genius Ways to Minimize Risk As An Options Trader\n\nhttps://t.co/3SikjPSsxk\n\n$spy $aapl $tsla', 'source': 'StockTwits Web', 'source_url': 'https://stocktwits.com', 'truncated': False, 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'author': User(_api= < tweepy.api.API object at 0x0000013ABA613A60 > , _json={'id': 950402063271424003, 'id_str': '950402063271424003', 'name': 'SmartOptions® Ai', 'screen_name': 'SmartOptionsAi', 'location': None, 'url': 'https://www.smartoptions.ai', 'description': 'CEO of SmartOptions®. Made millions in the market. Highly Profitable Options Signals Powered by Artificial Intelligence.', 'translator_type': 'none', 'protected': False, 'verified': False, 'followers_count': 3285, 'friends_count': 74, 'listed_count': 47, 'favourites_count': 583, 'statuses_count': 3908, 'created_at': 'Mon Jan 08 16:21:24 +0000 2018', 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'profile_background_color': '000000', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_link_color': '1B95E0', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000', 'profile_use_background_image': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', 
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/950402063271424003/1599668618', 
        'default_profile': False, 
        'default_profile_image': False, 
        'following': None, 
        'follow_request_sent': None, 
        'notifications': None
    }, 
    id=950402063271424003, 
    id_str='950402063271424003', 
    name='SmartOptions® Ai', 
    screen_name='SmartOptionsAi', 
    location=None, 
    url='https://www.smartoptions.ai', 
    description='CEO of SmartOptions®. Made millions in the market. Highly Profitable Options Signals Powered by Artificial Intelligence.', 
    translator_type='none', 
    protected=False, 
    verified=False, 
    followers_count=3285, 
    friends_count=74, 
    listed_count=47, 
    favourites_count=583, 
    statuses_count=3908, 
    created_at=datetime.datetime(2018, 1, 8, 16, 21, 24), 
    utc_offset=None, 
    time_zone=None, 
    geo_enabled=False, 
    lang=None, 
    contributors_enabled=False, 
    is_translator=False, 
    profile_background_color='000000', 
    profile_background_image_url='http://abs.twimg.com/images/themes/theme1/bg.png', 
    profile_background_image_url_https='https://abs.twimg.com/images/themes/theme1/bg.png', 
    profile_background_tile=False, 
    profile_link_color='1B95E0', 
    profile_sidebar_border_color='000000', 
    profile_sidebar_fill_color='000000', 
    profile_text_color='000000', 
    profile_use_background_image=False, 
    profile_image_url='http://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', 
    profile_image_url_https='https://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', 
    profile_banner_url='https://pbs.twimg.com/profile_banners/950402063271424003/1599668618', 
    default_profile=False, 
    default_profile_image=False, 
    following=False, 
    follow_request_sent=None, 
    notifications=None), 
    'user': User(_api=<tweepy.api.API object at 0x0000013ABA613A60>, _json={'id': 950402063271424003, 'id_str': '950402063271424003', 'name': 'SmartOptions® Ai', 'screen_name': 'SmartOptionsAi', 'location': None, 'url': 'https://www.smartoptions.ai', 'description': 'CEO of SmartOptions®. Made millions in the market. Highly Profitable Options Signals Powered by Artificial Intelligence.', 'translator_type': 'none', 'protected': False, 'verified': False, 'followers_count': 3285, 'friends_count': 74, 'listed_count': 47, 'favourites_count': 583, 'statuses_count': 3908, 'created_at': 'Mon Jan 08 16:21:24 +0000 2018', 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'profile_background_color': '000000', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_link_color': '1B95E0', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000', 'profile_use_background_image': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/950402063271424003/1599668618', 'default_profile': False, 'default_profile_image': False, 'following': None, 'follow_request_sent': None, 'notifications': None}, id=950402063271424003, id_str='950402063271424003', name='SmartOptions® Ai', screen_name='SmartOptionsAi', location=None, url='https://www.smartoptions.ai', description='CEO of SmartOptions®. Made millions in the market. Highly Profitable Options Signals Powered by Artificial Intelligence.', translator_type='none', protected=False, verified=False, followers_count=3285, friends_count=74, listed_count=47, favourites_count=583, statuses_count=3908, created_at=datetime.datetime(2018, 1, 8, 16, 21, 24), utc_offset=None, time_zone=None, geo_enabled=False, lang=None, contributors_enabled=False, is_translator=False, profile_background_color='000000', profile_background_image_url='http://abs.twimg.com/images/themes/theme1/bg.png', profile_background_image_url_https='https://abs.twimg.com/images/themes/theme1/bg.png', profile_background_tile=False, profile_link_color='1B95E0', profile_sidebar_border_color='000000', profile_sidebar_fill_color='000000', profile_text_color='000000', profile_use_background_image=False, profile_image_url='http://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1303730791910907905/YG-18qdh_normal.jpg', profile_banner_url='https://pbs.twimg.com/profile_banners/950402063271424003/1599668618', default_profile=False, default_profile_image=False, following=False, follow_request_sent=None, notifications=None), 'geo': None, 'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False, 'quote_count': 0, 'reply_count': 0, 'retweet_count': 0, 'favorite_count': 0, 'entities': {'hashtags': [], 'urls': [{'url': 'https://t.co/3SikjPSsxk', 'expanded_url': 'http://smartoptions.ai/post/minimize-risk', 'display_url': 'smartoptions.ai/post/minimize-…', 'indices': [53, 76]}], 'user_mentions': [], 'symbols': [{'text': 'spy', 'indices': [78, 82]}, {'text': 'aapl', 'indices': [83, 88]}, {'text': 'tsla', 'indices': [89, 94]}]}, 'favorited': False, 'retweeted': False, 'possibly_sensitive': False, '
    filter_level': 'low', 
    'lang': 'en', 
    'matching_rules': [{'tag': None}]}
